// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"database/sql"
)

type Death struct {
	Namespace string
	RoomID    string
	UserID    string
	Count     sql.NullInt32
}

type Game struct {
	Namespace    string
	RoomID       string
	ChannelID    string
	PotatoKind   string
	HeatLevel    int32
	HolderUserID string
	Turns        int32
	Finished     bool
	CreatedAt    sql.NullTime
}

type Room struct {
	Namespace string
	ID        string
	CreatedAt sql.NullTime
}
